name: Run Tests

on:
  push:
    branches: [ "main", "adding-test-cases" ]
  pull_request:
    branches: [ "main", "adding-test-cases" ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: Run backend tests
        run: npm test
        working-directory: ./backend
